//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GmodAddonCompressor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int _imageWidthLimitIndex {
            get {
                return ((int)(this["_imageWidthLimitIndex"]));
            }
            set {
                this["_imageWidthLimitIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int _imageHeightLimitIndex {
            get {
                return ((int)(this["_imageHeightLimitIndex"]));
            }
            set {
                this["_imageHeightLimitIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _useFFMpegForCompress {
            get {
                return ((bool)(this["_useFFMpegForCompress"]));
            }
            set {
                this["_useFFMpegForCompress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _unlockedUI {
            get {
                return ((bool)(this["_unlockedUI"]));
            }
            set {
                this["_unlockedUI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _compressVTF {
            get {
                return ((bool)(this["_compressVTF"]));
            }
            set {
                this["_compressVTF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _compressWAV {
            get {
                return ((bool)(this["_compressWAV"]));
            }
            set {
                this["_compressWAV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _compressMP3 {
            get {
                return ((bool)(this["_compressMP3"]));
            }
            set {
                this["_compressMP3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _compressOGG {
            get {
                return ((bool)(this["_compressOGG"]));
            }
            set {
                this["_compressOGG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _compressJPG {
            get {
                return ((bool)(this["_compressJPG"]));
            }
            set {
                this["_compressJPG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _compressPNG {
            get {
                return ((bool)(this["_compressPNG"]));
            }
            set {
                this["_compressPNG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _compressLUA {
            get {
                return ((bool)(this["_compressLUA"]));
            }
            set {
                this["_compressLUA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _changeOriginalCodeToMinimalistic {
            get {
                return ((bool)(this["_changeOriginalCodeToMinimalistic"]));
            }
            set {
                this["_changeOriginalCodeToMinimalistic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _reduceExactlyToLimits {
            get {
                return ((bool)(this["_reduceExactlyToLimits"]));
            }
            set {
                this["_reduceExactlyToLimits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _reduceExactlyToResolution {
            get {
                return ((bool)(this["_reduceExactlyToResolution"]));
            }
            set {
                this["_reduceExactlyToResolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _keepImageAspectRatio {
            get {
                return ((bool)(this["_keepImageAspectRatio"]));
            }
            set {
                this["_keepImageAspectRatio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _imageMagickVTFCompress {
            get {
                return ((bool)(this["_imageMagickVTFCompress"]));
            }
            set {
                this["_imageMagickVTFCompress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint _imageSkipWidth {
            get {
                return ((uint)(this["_imageSkipWidth"]));
            }
            set {
                this["_imageSkipWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint _imageSkipHeight {
            get {
                return ((uint)(this["_imageSkipHeight"]));
            }
            set {
                this["_imageSkipHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22050")]
        public int _wavRate {
            get {
                return ((int)(this["_wavRate"]));
            }
            set {
                this["_wavRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int _wavRateListIndex {
            get {
                return ((int)(this["_wavRateListIndex"]));
            }
            set {
                this["_wavRateListIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int _imageReducingResolutionListIndex {
            get {
                return ((int)(this["_imageReducingResolutionListIndex"]));
            }
            set {
                this["_imageReducingResolutionListIndex"] = value;
            }
        }
    }
}
